name: Deploy and tests
on:
  push:
    branches:
      - "master"

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install deps
        working-directory: ./
        run: |
          npm ci
          

      - name: Build CLI
        working-directory: ./
        run: |
          make build_cli
          echo "language core; fn main(n : Nat) -> Nat { return 0 }" | make cli
          echo "language core; fn main(n : Nat) -> Nat { return false }" | make cli && { exit 1; } || exit 0

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        working-directory: ./
        run: |
          CI=true npm test
